development:
  adapter: '<%= ENV['RDS_ADAPTER'] %>'
  database: '<%= ENV['RDS_DATABASE'] %>'
  username: '<%= ENV['RDS_USERNAME'] %>'
  password: '<%= ENV['RDS_PASSWORD'] %>'
  host: '<%= ENV['RDS_HOST'] %>'
  port: 5432

test:
  adapter: postgresql
  encoding: unicode
  database: sample_postgres_test
  pool: 5
  username: sample_postgres
  password:

production:
  adapter: '<%= ENV['RDS_ADAPTER'] %>'
  database: '<%= ENV['RDS_DATABASE'] %>'
  username: '<%= ENV['RDS_USERNAME'] %>'
  password: '<%= ENV['RDS_PASSWORD'] %>'
  host: '<%= ENV['RDS_HOST'] %>'
  port: 5432
