
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_online_store_development

test:
  <<: *default
  database: rails_online_store_test

production:
  <<: *default
  database: rails_online_store_production
  username: deploy
  password: Rails.application.credentials.dig(:production, :db_password)
