default:
  navigation:
    - title: Körbe
      subtitle: Kategorien
      url: /t/produkte/korbe
      items:
        - :title: Einkaufkörbe
          :url: /t/produkte/korbe/einkaufskorbe
        - :title: Erntekörbe
          :url: /t/produkte/korbe/erntekorbe
        - :title: Brotkörbe
          :url: /t/produkte/korbe/brotkorbe
        - :title: Kaminholzkörbe
          :url: /t/produkte/korbe/kaminholzkorbe
        - :title: Geschenkkörbe
          :url: /t/produkte/korbe/geschenkkorbe
        - :title: Dekokörbe
          :url: /t/produkte/korbe/dekokorbe
        - :title: Katzenmöbel
          :url: /t/produkte/korbe/katzenmobel
        - :title: Hundemöbel
          :url: /t/produkte/korbe/hundemobel
        - :title: Weindenkörbe
          :url: /t/produkte/korbe/weidenkorbe
      promo_banners:
        - subtitle: Erntekörbe
          title: 10% Billiger
          url: /products/einkaufskorb-weide-hell-oval-henkel-40-x-26-x-25-42
          image: 'meganav/promo_banner_left-first-category.jpg'
        - subtitle: Katzenkörbe
          title: Neue Modelle
          url: http://localhost:3000/products/katzensessel-weide-katzenkorb-aus-heller-weide
          image: 'meganav/promo_banner_right-first-category.jpg'
    - title: Naturzäune
      subtitle: Kategorien
      url: /t/produkte/zaune
      items:
        - :title: Weidenzäune
          :url: /t/produkte/zaune/weidenenzaune
        - :title: Haselnusszäune
          :url: /t/produkte/zaune/haselnusszaune
        - :title: Robinenzäunte
          :url: /t/produkte/zaune/robinienzaune
        - :title: Lärchenzäune
          :url: /t/produkte/zaune/larchenzaune
      promo_banners:
        - subtitle: Neue Modelle
          title: 10% Billiger
          url: /products/einkaufskorb-weide-hell-oval-henkel-40-x-26-x-25-42
          image: 'meganav/promo_banner_left-second-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-second-category.jpg'
    - title: Gartengestaltung
      subtitle: Kategorien
      url: /t/produkte/gartengestaltung
      items:
        - :title: Hochbeete
          :url: /t/produkte/gartengestaltung/hochbeete
        - :title: Pflanzkästen
          :url: /t/produkte/gartengestaltung/pflanzkasten
        - :title: Vögelhäuser
          :url: /t/produkte/gartengestaltung/voegelhauser
        - :title: Gewächshäuser
          :url: /t/produkte/gartengestaltung/gewachshauser
      promo_banners:
        - subtitle: New collection
          title: Summer 2019
          url: /t/new-collection/summer-2019
          image: 'meganav/promo_banner_left-third-category.jpg'
        - subtitle: Special Offers
          title: Get up to 30% off
          url: /t/special-offers/30-off
          image: 'meganav/promo_banner_right-third-category.jpg'
